source:
  adapter: mysql2
  host: localhost
  database: mysql_transfer_test
  username: root
  password:
  encoding: utf8

target:
  adapter: postgres
  host: localhost
  database: pg_transfer_test
  username: postgres
  password:
  encoding: utf8

worker:
  stop_on_error: true

mode: full
