source:
  adapter: mysql2
  host: localhost
  database: source_db
  user: root
  password:
  encoding: utf8

target:
  adapter: postgres
  host: localhost
  database: target_db
  user: postgres
  password:
  encoding: utf8

# these tables will be skipped
#exclude_tables:
#  - schema_migrations

# these target tables wil be truncated before copy data into
#truncate_tables:
#  - roles
#  - users

